- name: Set JBoss EAP Download Facts
  set_fact:
    jboss_eap_artifact_url: "{{ jboss_eap_artifact_source }}/{{ jboss_eap_artifact_name }}"
    jboss_eap_artifact_dl_dest: "{{ jboss_eap_artifacts_dl_dest_dir }}"

#### Defensive Programming To Check If EAP Is Already Installed
- name: Check Existence of Libraries
  become: true
  stat:
    path: "{{ jboss_eap_library_dest_dir + '/' + '/version.txt' }}"
  register: jboss_eap_exists

- name: Download JBoss EAP from JFrog Artifact
  get_url:
    url: "{{ jboss_eap_artifact_url }}"
    dest: "{{ jboss_eap_artifact_dl_dest }}"
    url_username: "{{ art_username | default(None) }}"
    url_password: "{{ art_password | default(None) }}"
    mode: 0755
    force_basic_auth: yes
  register: url_jboss_eap_download
  when: not jboss_eap_exists.stat.exists

- name: Create JBoss EAP Group
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "{{ jboss_eap_group_gid | default('400') }}"

- name: Create JBoss EAP User
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "{{ jboss_eap_user_uid | default('400') }}"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_library_dest_dir }}"
    shell: "/bin/bash"

- name: Extract JBoss EAP Libraries
  become: true
  unarchive:
    #src: "/opt/jboss-eap-7.3.0.zip"
    #dest: "/opt"
    src: "{{ jboss_eap_artifacts_dl_dest_dir }}/jboss-eap-7.3.0.zip"
    dest: "{{ jboss_eap_artifacts_dl_dest_dir }}"
    #creates: "{{ jboss_eap_home_dir_name }}"
    #copy: no
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    remote_src: yes
  when: not jboss_eap_exists.stat.exists
  register: jboss_install

- name: Set JBoss EAP Service Directories Facts
  set_fact:
    jboss_eap_home: "{{ jboss_eap_library_dest_dir }}"
  register: jboss_home_result
