- name: "include base vars file"
  include_vars: vars/basevars.yml

- name: remove openjdk
  command: rm -rf java-11-openjdk
  args:
    chdir: "{{ openjdk_artifacts_dl_dest_dir }}"


- name: remove openjdk tar file
  command: rm -rf java-11-openjdk-11.0.13.0.8-1.portable.jdk.el.x86_64.tar.xz
  args:
    chdir: "{{ openjdk_artifacts_dl_dest_dir }}"
