#Task to install Java ( RedHat OpenJDK )

- name: ensure Java directory exists
  file:
    path: "{{ java_directory }}"
    state: directory
    mode: 0755

- name: "Unzip Java file"
  unarchive:
    src: '{{ pkg_folder }}//{{ java_pack }}'
    dest: "{{ java_directory }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Alternatives Java link created
  alternatives:
          name: java
          link: /usr/bin/java
          path: "{{ alt_java_link }}"
          priority: 1

- name: Alternatives Javac link created
  alternatives:
          name: javac
          link: /usr/bin/javac
          path: "{{ alt_java_link_c }}"
          priority: 1

- name: Update Profile with Java Home variable
  lineinfile:
          path: /etc/profile
          state: present
          regexp: "export JAVA_HOME"
          line: 'export JAVA_HOME="{{ java_directory }}"'

- name: Update Path with Java Home variable
  lineinfile:
          path: /etc/profile
          line: 'export PATH=$PATH:$JAVA_HOME/bin'

- name: Source Profile File
  shell:
          cmd: source /etc/profile