
- name: Download DynaTrace locally
  shell: |
    wget -O /tmp/Dynatrace-OneAgent-Linux.sh "https://yxu53411.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86&flavor=default"

- name: Verify Signature
  shell: |
    wget https://ca.dynatrace.com/dt-root.cert.pem ; ( echo 'Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="--SIGNED-INSTALLER"'; echo ; echo ; echo '----SIGNED-INSTALLER' ; cat /tmp/Dynatrace-OneAgent-Linux.sh ) | openssl cms -verify -CAfile dt-root.cert.pem > /dev/null

- name: create Data Folder
  file:
    state: directory
    path: /data
    mode: 755


- name: Run the installer
  shell: /bin/sh /tmp/Dynatrace-OneAgent-Linux.sh   INSTALL_PATH=/data --set-app-log-content-access=false --set-infra-only=false --set-host-group={{ group_names[0] }}

- name: Start Dynatrace OneAgentservice, if not running
  service:
    name: oneagent
    state: started
  register: oneagent

- name: Enable Dynatrace
  command: systemctl enable oneagent

- debug: var=oneagent.state

- name: remove Dynatrace install file
  shell: rm -f /tmp/Dynatrace-OneAgent-Linux.sh
  when: oneagent.state == "started"

