# Java Installation

- name: Install prerequisites
  hosts: Bravo
  tasks:
  - name: Install wget & yum-utils
    yum:
        name:
                - wget
                - yum-utils
                -  yum-plugin-versionlock
        state: latest

- name: Install Java {{ java_version }} OpenJDK for XSB
  hosts: Bravo
  vars_files:
        - vars/base.yml
  tasks:
        - name: Install Java {{ java_version }} OpenJDK
          include: tasks/java.yml

