# Redis Installation

- name: Install prerequisites
  hosts: Bravo
  tasks:
  - name: Install wget & yum-utils
    yum:
        name:
                - wget
                - yum-utils
                -  yum-plugin-versionlock
        state: latest

- name: Install Redis
  hosts: Bravo
  vars_files:
        - vars/base.yml
  tasks:
        - name: Install Redis
          include: tasks/redis.yml