- name: stat EAP home dir
  stat: path={{ jboss_eap_library_dest_dir }}/{{ jboss_eap_home_dir_name }}
  register: eap_home_result
    
- name: Move EAP files to EAP Home dir
  command:
    mv "{{ pkg_folder }}/{{ extract_folder }}" {{ jboss_eap_library_dest_dir }}
  when: not eap_home_result.stat.exists

#### Defensive Programming To Check If EAP Is Already Installed
- name: Check Existence of Libraries
  become: true
  stat:
    path: "{{ jboss_eap_library_dest_dir  + '/version.txt' }}"
  register: jboss_eap_exists

- name: Create JBoss EAP Group
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "{{ jboss_eap_group_gid | default('400') }}"

- name: Create JBoss EAP User
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "{{ jboss_eap_user_uid | default('400') }}"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_library_dest_dir }}"
    shell: "/bin/bash"

- name: Change Owner of EAP Dir
  file:
    path: "{{ jboss_eap_library_dest_dir }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    recurse: yes

- name: Set JBoss EAP Service Directories Facts
  set_fact:
    jboss_eap_home: "{{ jboss_eap_library_dest_dir }}"
  register: jboss_home_result

