##################################
### Ansible Credentials Script ###
###     Roy Lofthouse 2020     ###
##################################

---
- hosts: '{{ target }}'
  tasks:

  - name: "Authorized Keys"
    authorized_key:
      user: "{{ ansible_ssh_user }}"
      key: "{{ lookup('file', ssh_key ) }}"
      state: present

  - name: "Update SSH Config"
    become: yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
      - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication yes' }
    notify:
      - Restart ssh
 
  handlers:
  - name: Restart ssh
    service:
      name=sshd
      state=restarted
